#!/bin/sh
# Xsetup - run as root before the login dialog appears
# Check if the second monitor is physically connected
xrandr --output HDMI-A-1 --auto --primary
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

